import { useMemo, useState } from 'react'
import '../dashboard.css'
import DepartmentCard from '../components/DepartmentCard'
import StatusFilter from '../components/StatusFilter'
import SearchBox from '../components/SearchBox'
import StatusForm from '../components/StatusForm'
import StatusOverview from '../components/StatusOverview'
import ResetPasswordDialog from '../components/ResetPasswordDialog'
import { formatDate, formatDateTime, today } from '../utils/status'

export default function Dashboard({ profile, data, onSignOut, goAdmin, goMonthly, goMeeting, goCalendar, onDateChange }) {
  const { employees, departments, loading, error, date, reload } = data
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [departmentFilter, setDepartmentFilter] = useState('all'); const [edit, setEdit] = useState(null); const [resetPassword, setResetPassword] = useState(false)
  const dashboardEmployees = useMemo(() => employees.map(employee => employee.displayStatus === 'meeting' ? { ...employee, displayStatus: 'working' } : employee), [employees])
  const visible = useMemo(() => dashboardEmployees.filter(employee => (filter === 'all' || employee.displayStatus === filter) && `${employee.full_name} ${employee.employee_code}`.toLowerCase().includes(query.toLowerCase())), [dashboardEmployees, filter, query])
  const leaders = departmentFilter === 'all' || departmentFilter === 'leadership' ? visible.filter(employee => !employee.department_id) : []
  const visibleDepartments = useMemo(() => departments.filter(department => departmentFilter === 'all' || department.id === departmentFilter).map(department => ({ ...department, employees: visible.filter(employee => employee.department_id === department.id) })).filter(department => department.employees.length > 0), [departments, visible, departmentFilter])
  const latest = employees.map(employee => employee.daily?.updated_at).filter(Boolean).sort().at(-1)
  return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">DAILY WORK STATUS</p><h1>HR Dashboard</h1><p className="subtle">{formatDate(date)} · Last updated: {formatDateTime(latest)}</p></div><div className="top-actions"><span className="user-chip">{profile.full_name}</span><a className="secondary-button update-link" href="#/update" target="_blank" rel="noreferrer" style={{ textDecoration: 'none' }}>Update</a>{profile.role === 'admin' && <><button className="secondary-button" onClick={goAdmin}>Administration</button><button className="secondary-button" onClick={goCalendar}>Work calendar</button><button className="secondary-button reset-button" onClick={() => setResetPassword(true)}>Reset password</button></>}<button className="text-button" onClick={onSignOut}>Sign out</button></div></header><nav aria-label="Dashboard pages" style={{ display: 'flex', gap: 10, marginBottom: 20 }}><button className="secondary-button" onClick={goMonthly}>Monthly statistics</button><button className="secondary-button" onClick={goMeeting}>Meeting Info</button></nav><StatusOverview employees={dashboardEmployees}/><section className="toolbar"><SearchBox value={query} onChange={setQuery}/><label className="dashboard-date">Display date<input type="date" min={today()} value={date} onChange={event => onDateChange(event.target.value)} /></label><StatusFilter value={filter} onChange={setFilter} departmentValue={departmentFilter} onDepartmentChange={setDepartmentFilter} departments={departments}/></section>{error && <p className="notice error">{error}</p>}{loading ? <p className="loading">Loading data...</p> : <>{leaders.length > 0 && <section className="leadership-section"><div className="leadership-list"><DepartmentCard department={{ name: 'Leadership' }} employees={leaders} editable={profile.role === 'admin'} onEmployeeClick={setEdit}/></div></section>}<section className="department-grid">{visibleDepartments.map(department => <DepartmentCard key={department.id} department={department} employees={department.employees} editable={profile.role === 'admin'} onEmployeeClick={setEdit}/>)}</section>{visible.length === 0 && <p className="empty">No matching employees found.</p>}</>}{edit && <div className="modal-backdrop"><div className="modal"><StatusForm employee={edit} onSaved={reload} onClose={() => setEdit(null)}/></div></div>}{resetPassword && <ResetPasswordDialog employees={employees} onClose={() => setResetPassword(false)} />}</main>
}
