import { useMemo, useState } from 'react'
import { useMonthlyStats } from '../hooks/useMonthlyStats'
import EmployeeMonthlyDetail from '../components/EmployeeMonthlyDetail'
import { today } from '../utils/status'

const currentMonth = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit' }).format(new Date()).slice(0, 7)
const moveMonth = (month, delta) => { const date = new Date(`${month}-01T12:00:00`); date.setMonth(date.getMonth() + delta); return date.toISOString().slice(0, 7) }
const departmentLabel = name => name === 'Ban lãnh đạo' ? 'Leadership' : name
const cutOffDate = () => new Intl.DateTimeFormat('en-GB').format(new Date(`${today()}T00:00:00`))

export default function MonthlyStatsPage({ goBack }) {
  const [month, setMonth] = useState(currentMonth()); const [query, setQuery] = useState(''); const [department, setDepartment] = useState('all'); const [statusOnly, setStatusOnly] = useState('all'); const [detail, setDetail] = useState(null)
  const { rows, calendar, loading, error } = useMonthlyStats(month); const departments = useMemo(() => [...new Set(rows.map(row => row.department_name))].sort(), [rows]); const shown = useMemo(() => rows.filter(row => (department === 'all' || row.department_name === department) && `${row.full_name} ${row.employee_code}`.toLowerCase().includes(query.toLowerCase()) && (statusOnly === 'all' || Number(row[`${statusOnly}_days`]) > 0)).sort((a, b) => a.full_name.localeCompare(b.full_name)), [rows, department, query, statusOnly])
  return <main className="app-shell monthly-page"><header className="topbar"><div><p className="eyebrow">WORK CALENDAR REPORT</p><h1>Monthly statistics</h1></div><button className="secondary-button" onClick={goBack}>← Back to dashboard</button></header><section className="monthly-controls"><button onClick={() => setMonth(moveMonth(month, -1))}>← Previous month</button><input type="month" value={month} onChange={event => setMonth(event.target.value)} /><button onClick={() => setMonth(moveMonth(month, 1))}>Next month →</button><button onClick={() => setMonth(currentMonth())}>Current month</button><input placeholder="Search by name or employee ID" value={query} onChange={event => setQuery(event.target.value)} /><select value={department} onChange={event => setDepartment(event.target.value)}><option value="all">All departments</option>{departments.map(name => <option key={name} value={name}>{departmentLabel(name)}</option>)}</select><select value={statusOnly} onChange={event => setStatusOnly(event.target.value)}><option value="all">All statuses</option><option value="sick">Sick leave</option><option value="leave">Annual leave</option><option value="business_trip">Business trip</option></select></section>{error && <p className="notice error">{error}</p>}<p className="subtle">{calendar.filter(day => day.day_type === 'working_day').length} scheduled workdays · Cut-off at {cutOffDate()}.</p>{loading ? <p className="loading">Loading statistics...</p> : <><div className="monthly-table-wrap"><table className="monthly-table"><thead><tr><th>No.</th><th>Employee ID</th><th>Full name</th><th>Department</th><th>Working</th><th>Business trip</th><th>Annual leave</th><th>Sick leave</th><th>Scheduled</th></tr></thead><tbody>{shown.map((row, index) => <tr key={row.employee_id} onClick={() => setDetail(row)}><td>{index + 1}</td><td>{row.employee_code}</td><td>{row.full_name}</td><td>{departmentLabel(row.department_name)}</td><td>{row.working_days}</td><td>{row.business_trip_days}</td><td>{row.leave_days}</td><td>{row.sick_days}</td><td>{row.scheduled_workdays}</td></tr>)}</tbody></table>{shown.length === 0 && <p className="empty">No matching data.</p>}</div>{detail && <EmployeeMonthlyDetail row={detail} month={month} calendar={calendar} onClose={() => setDetail(null)} />}</>}</main>
}
