import { useMemo, useState } from 'react'
import { useMonthlyStats } from '../hooks/useMonthlyStats'
import EmployeeMonthlyDetail from '../components/EmployeeMonthlyDetail'

const currentMonth = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit' }).format(new Date()).slice(0, 7)
const moveMonth = (month, delta) => { const d = new Date(`${month}-01T12:00:00`); d.setMonth(d.getMonth() + delta); return d.toISOString().slice(0, 7) }

export default function MonthlyStatsPage({ goBack }) {
  const [month, setMonth] = useState(currentMonth()); const [query, setQuery] = useState(''); const [department, setDepartment] = useState('all'); const [statusOnly, setStatusOnly] = useState('all'); const [detail, setDetail] = useState(null)
  const { rows, calendar, loading, error } = useMonthlyStats(month)
  const departments = useMemo(() => [...new Set(rows.map(row => row.department_name))].sort(), [rows])
  const shown = useMemo(() => rows.filter(row => (department === 'all' || row.department_name === department) && (`${row.full_name} ${row.employee_code}`).toLowerCase().includes(query.toLowerCase()) && (statusOnly === 'all' || Number(row[`${statusOnly}_days`]) > 0)).sort((a, b) => a.full_name.localeCompare(b.full_name)), [rows, department, query, statusOnly])
  return <main className="app-shell monthly-page"><header className="topbar"><div><p className="eyebrow">BÁO CÁO THEO LỊCH LÀM VIỆC</p><h1>Thống kê tháng</h1></div><button className="secondary-button" onClick={goBack}>← Về dashboard</button></header><section className="monthly-controls"><button onClick={() => setMonth(moveMonth(month, -1))}>← Tháng trước</button><input type="month" value={month} onChange={event => setMonth(event.target.value)} /><button onClick={() => setMonth(moveMonth(month, 1))}>Tháng sau →</button><button onClick={() => setMonth(currentMonth())}>Tháng hiện tại</button><input placeholder="Tìm tên hoặc mã nhân viên" value={query} onChange={event => setQuery(event.target.value)} /><select value={department} onChange={event => setDepartment(event.target.value)}><option value="all">Tất cả phòng ban</option>{departments.map(name => <option key={name}>{name}</option>)}</select><select value={statusOnly} onChange={event => setStatusOnly(event.target.value)}><option value="all">Tất cả trạng thái</option><option value="sick">Có nghỉ ốm</option><option value="leave">Có nghỉ phép</option><option value="business_trip">Có công tác</option></select></section>{error && <p className="notice error">{error}</p>}<p className="subtle">{calendar.filter(day => day.day_type === 'working_day').length} ngày làm việc theo lịch · Các ngày sau hôm nay được tính là 0.</p>{loading ? <p className="loading">Đang tải thống kê...</p> : <><div className="monthly-table-wrap"><table className="monthly-table"><thead><tr><th>STT</th><th>Mã NV</th><th>Họ và tên</th><th>Phòng/Bộ phận</th><th>Đi làm</th><th>Công tác</th><th>Nghỉ phép</th><th>Nghỉ ốm</th><th>Theo lịch</th></tr></thead><tbody>{shown.map((row, index) => <tr key={row.employee_id} onClick={() => setDetail(row)}><td>{index + 1}</td><td>{row.employee_code}</td><td>{row.full_name}</td><td>{row.department_name}</td><td>{row.working_days}</td><td>{row.business_trip_days}</td><td>{row.leave_days}</td><td>{row.sick_days}</td><td>{row.scheduled_workdays}</td></tr>)}</tbody></table>{shown.length === 0 && <p className="empty">Không có dữ liệu phù hợp.</p>}</div>{detail && <EmployeeMonthlyDetail row={detail} month={month} calendar={calendar} onClose={() => setDetail(null)} />}</>}</main>
}
