import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'

const currentMonth = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh', year: 'numeric', month: '2-digit' }).format(new Date()).slice(0, 7)
export default function WorkCalendarPage({ goBack }) {
  const [month, setMonth] = useState(currentMonth()); const [days, setDays] = useState([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = async () => { const start = `${month}-01`; const end = new Date(`${start}T12:00:00`); end.setMonth(end.getMonth() + 1); const { data, error: resultError } = await supabase.from('work_calendar').select('*').gte('date', start).lt('date', end.toISOString().slice(0,10)).order('date'); if (resultError) setError(resultError.message); setDays(data || []) }
  useEffect(() => { load() }, [month])
  const save = async day => { setSaving(true); const { error: resultError } = await supabase.from('work_calendar').upsert(day); setSaving(false); if (resultError) return setError(resultError.message); load() }
  return <main className="app-shell calendar-page"><header className="topbar"><div><p className="eyebrow">ADMIN ONLY</p><h1>Lịch làm việc</h1></div><button className="secondary-button" onClick={goBack}>← Về dashboard</button></header><section className="calendar-admin"><label>Tháng<input type="month" value={month} onChange={event => setMonth(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<table className="monthly-table"><thead><tr><th>Ngày</th><th>Loại ngày</th><th>Tên ngày lễ / ghi chú</th><th /></tr></thead><tbody>{days.map(day => <CalendarRow key={day.date} day={day} disabled={saving} onSave={save} />)}</tbody></table></section></main>
}
function CalendarRow({ day, disabled, onSave }) { const [type, setType] = useState(day.day_type); const [name, setName] = useState(day.holiday_name || ''); return <tr><td>{day.date}</td><td><select value={type} onChange={event => setType(event.target.value)}><option value="working_day">Ngày làm việc</option><option value="weekend">Cuối tuần</option><option value="holiday">Ngày lễ</option><option value="special_leave">Nghỉ đặc biệt</option></select></td><td><input value={name} onChange={event => setName(event.target.value)} placeholder="Ví dụ: Quốc khánh" /></td><td><button disabled={disabled} onClick={() => onSave({ ...day, day_type: type, holiday_name: name.trim() || null })}>Lưu</button></td></tr> }
