import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import { STATUS, statusLabel, formatDateTime } from '../utils/status'

export default function EmployeeMonthlyDetail({ row, month, calendar, onClose }) {
  const [statuses, setStatuses] = useState([])
  const start = `${month}-01`; const next = new Date(`${start}T12:00:00`); next.setMonth(next.getMonth() + 1); const end = next.toISOString().slice(0, 10)
  useEffect(() => { supabase.from('daily_status').select('*').eq('employee_id', row.employee_id).gte('date', start).lt('date', end).then(({ data }) => setStatuses(data || [])) }, [row.employee_id, start, end])
  const statusByDate = useMemo(() => new Map(statuses.map(status => [status.date, status])), [statuses])
  const calendarByDate = useMemo(() => new Map(calendar.map(day => [day.date, day])), [calendar])
  const days = Array.from({ length: next.getDate() ? new Date(next.getFullYear(), next.getMonth(), 0).getDate() : 0 }, (_, index) => `${month}-${String(index + 1).padStart(2, '0')}`)
  return <div className="modal-backdrop"><section className="monthly-detail modal"><button className="close detail-close" onClick={onClose}>×</button><p className="eyebrow">CHI TIẾT THÁNG {month}</p><h2>{row.full_name}</h2><p className="subtle">{row.employee_code} · {row.department_name}</p><div className="detail-totals"><span>Đi làm <b>{row.working_days}</b></span><span>Công tác <b>{row.business_trip_days}</b></span><span>Nghỉ phép <b>{row.leave_days}</b></span><span>Nghỉ ốm <b>{row.sick_days}</b></span><span>Theo lịch <b>{row.scheduled_workdays}</b></span></div><div className="month-weekdays">{['T2','T3','T4','T5','T6','T7','CN'].map(day => <span key={day}>{day}</span>)}</div><div className="month-calendar">{Array.from({ length: (new Date(`${month}-01T12:00:00`).getDay() + 6) % 7 }, (_, i) => <i key={`blank-${i}`} />)}{days.map(date => { const calendarDay = calendarByDate.get(date); const record = statusByDate.get(date); const type = calendarDay?.day_type || 'weekend'; const currentStatus = type === 'working_day' ? (record?.status || 'working') : null; const title = record ? `${date} · ${statusLabel(record.status)}${record.note ? ` · ${record.note}` : ''} · ${formatDateTime(record.updated_at)}` : `${date} · ${calendarDay?.holiday_name || (type === 'working_day' ? 'Đi làm' : type)}`; return <button key={date} title={title} className={`calendar-day ${currentStatus || type} ${record && type !== 'working_day' ? 'invalid-status' : ''}`}><b>{Number(date.slice(-2))}</b>{calendarDay?.holiday_name && <small>{calendarDay.holiday_name}</small>}{record && <span>{statusLabel(record.status)}</span>}</button> })}</div><p className="subtle">Viền cam: có dữ liệu trạng thái trên ngày không phải ngày làm việc; không được tính vào thống kê.</p></section></div>
}
