import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import { STATUS, today } from '../utils/status'
import './MyScheduleOverview.css'

const startOfCurrentWeek = () => { const date = new Date(`${today()}T12:00:00`); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date }
const dateKey = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const nonWorkingInfo = day => ({ weekend: { label: 'Weekend', color: '#9aa6b2' }, holiday: { label: day.holiday_name || 'Holiday', color: '#b0bac6' }, special_leave: { label: day.holiday_name || 'Special leave', color: '#b0bac6' } }[day.day_type])

export default function MyScheduleOverview({ employeeId }) {
  const [records, setRecords] = useState([]); const [meetings, setMeetings] = useState([]); const [calendar, setCalendar] = useState([]); const [loading, setLoading] = useState(true)
  const days = useMemo(() => { const start = startOfCurrentWeek(); return Array.from({ length: 14 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return { key: dateKey(date), weekday: new Intl.DateTimeFormat('en-GB', { weekday: 'short' }).format(date), day: date.getDate(), month: new Intl.DateTimeFormat('en-GB', { month: 'short' }).format(date) } }) }, [])
  useEffect(() => { const start = days[0].key; const end = new Date(`${days.at(-1).key}T12:00:00`); end.setDate(end.getDate() + 1); const endKey = dateKey(end); Promise.all([supabase.from('daily_status').select('date,status,content,location').eq('employee_id', employeeId).gte('date', start).lt('date', endKey), supabase.from('employee_meetings').select('id,organizer_id,date,start_time,end_time,content,location').gte('date', start).lt('date', endKey).order('start_time'), supabase.from('employee_meeting_attendees').select('meeting_id').eq('employee_id', employeeId), supabase.from('work_calendar').select('date,day_type,holiday_name').gte('date', start).lt('date', endKey)]).then(([statusResult, meetingResult, attendeeResult, calendarResult]) => { const attendedIds = new Set((attendeeResult.data || []).map(item => item.meeting_id)); setRecords(statusResult.data || []); setMeetings((meetingResult.data || []).filter(meeting => meeting.organizer_id === employeeId || attendedIds.has(meeting.id))); setCalendar(calendarResult.data || []); setLoading(false) }) }, [employeeId, days])
  const statusByDate = useMemo(() => new Map(records.map(record => [record.date, record])), [records]); const meetingsByDate = useMemo(() => meetings.reduce((map, meeting) => { map.set(meeting.date, [...(map.get(meeting.date) || []), meeting]); return map }, new Map()), [meetings]); const calendarByDate = useMemo(() => new Map(calendar.map(day => [day.date, day])), [calendar])
  return <section className="my-schedule"><div className="my-schedule-heading"><div><p className="eyebrow">MY SCHEDULE</p><h2>This week & next week</h2></div><span>{loading ? 'Loading...' : '14 days'}</span></div><div className="my-schedule-grid">{days.map(day => { const record = statusByDate.get(day.key); const dayMeetings = meetingsByDate.get(day.key) || []; const fallbackType = new Date(`${day.key}T12:00:00`).getDay() % 6 === 0 ? 'weekend' : 'working_day'; const calendarDay = calendarByDate.get(day.key) || { day_type: fallbackType }; const isWorkingDay = calendarDay.day_type === 'working_day'; const effectiveStatus = dayMeetings.length ? 'meeting' : record?.status || 'working'; const info = isWorkingDay ? STATUS[effectiveStatus] : nonWorkingInfo(calendarDay); const isToday = day.key === today(); const meetingDetails = dayMeetings.map(meeting => `Time: ${meeting.start_time?.slice(0, 5) || '-'} - ${meeting.end_time?.slice(0, 5) || '-'}\nContent: ${meeting.content || '-'}\nLocation: ${meeting.location || '-'}`).join('\n\n'); const details = !isWorkingDay ? calendarDay.holiday_name || info.label : dayMeetings.length ? meetingDetails : record?.status === 'business_trip' ? `Content: ${record.content || '-'}\nLocation: ${record.location || '-'}` : info.label; return <article key={day.key} className={`schedule-day ${isToday ? 'is-today' : ''} ${isWorkingDay ? '' : 'is-non-working'}`} style={{ '--schedule-color': info.color }}><small>{day.weekday}</small><strong>{day.day}</strong><em>{day.month}</em><span>{isToday ? `Today · ${info.label}` : info.label}</span><div className="schedule-tooltip">{details}</div></article> })}</div><div className="my-schedule-legend">{Object.entries(STATUS).map(([key, item]) => <span key={key}><i style={{ background: item.color }} />{item.label}</span>)}<span><i style={{ background: '#9aa6b2' }} />Weekend / holiday</span></div></section>
}
